import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
await db.exec(fs.readFileSync('database/schema.sql','utf8'));
const admin='11111111-1111-4111-8111-111111111111',a='22222222-2222-4222-8222-222222222222',b='33333333-3333-4333-8333-333333333333',device='44444444-4444-4444-8444-444444444444';
await db.query('insert into auth.users values ($1),($2),($3)',[admin,a,b]);await db.query(`insert into public.profiles(id,name,role,employee) values ($1,'מנהל','admin',null),($2,'ירון גברי','agent','ירון גברי'),($3,'אוריאל כהן','agent','אוריאל כהן')`,[admin,a,b]);
await db.exec('set role authenticated');async function as(id){await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id])}async function fail(fn,msg){try{await fn();throw new Error('Expected rejection')}catch(e){assert.match(e.message,msg)}}
await as(admin);const item={id:device,serial:'TEST-001',model:'Reach R-Li',side:'ימין',color:'כסף',company:'אודיוטק',batch:'TEST',received:'2026-10-07'};await db.query('select receive_devices($1)',[JSON.stringify([item])]);await fail(()=>db.query('select receive_devices($1)',[JSON.stringify([{...item,id:'55555555-5555-4555-8555-555555555555',serial:'test-001'}])]),/מספר סידורי/);
await db.query('select move_device($1,$2,$3,$4)',[device,1,'assign',JSON.stringify({company:'אודיוטק',employee:'ירון גברי'})]);
await as(b);assert.equal((await db.query('select * from devices')).rows.length,0);assert.equal((await db.query('select * from events')).rows.length,0);await fail(()=>db.query('select move_device($1,$2,$3,$4)',[device,2,'deliver',JSON.stringify({client:'לקוח'})]),/אין הרשאה/);
await as(a);assert.equal((await db.query('select * from devices')).rows.length,1);await fail(()=>db.query('select receive_devices($1)',[JSON.stringify([item])]),/רק מנהל/);await fail(()=>db.query('select move_device($1,$2,$3,$4)',[device,2,'reassign',JSON.stringify({employee:'אוריאל כהן',company:'אודיוטק'})]),/אין הרשאה/);await fail(()=>db.query("update devices set data='{}'"),/permission denied/);
await db.query('select move_device($1,$2,$3,$4)',[device,2,'trial',JSON.stringify({client:'לקוח בדיקה',trialUntil:'2026-12-20'})]);await fail(()=>db.query('select move_device($1,$2,$3,$4)',[device,2,'deliver',JSON.stringify({client:'לקוח'})]),/עודכן/);await db.query('select move_device($1,$2,$3,$4)',[device,3,'deliver',JSON.stringify({client:'לקוח בדיקה'})]);await db.query('select move_device($1,$2,$3,$4)',[device,4,'return',JSON.stringify({reason:'בדיקה'})]);assert.equal((await db.query('select * from devices')).rows.length,0);
await as(admin);await fail(()=>db.query('select move_device($1,$2,$3,$4)',[device,5,'approve',JSON.stringify({checked:false})]),/אישור/);await db.query('select move_device($1,$2,$3,$4)',[device,5,'approve',JSON.stringify({checked:true})]);const result=(await db.query('select * from devices')).rows[0];assert.equal(result.data.status,'warehouse');assert.equal(result.version,6);assert.equal((await db.query('select * from events')).rows.length,6);console.log('PASS: SQL deployment, row-level employee isolation, forbidden writes, admin reception, case-insensitive serial uniqueness, stale update rejection, full trial/delivery/return/restock transactions and audit');await db.close();
